// Auto-generated by pipeline — Layout: default
export const businessData = {
  name: "YH Studios Photo Studio",
  category: "Photography studio",
  address: "\nThe One Tower, Suite 2901, Barsha Heights - Barsha Heights - Dubai - United Arab Emirates",
  phone: "\n+971 52 834 9964",
  email: "",
  website: "https://www.yhstudiosdxb.com/",
  mapUrl: "https://www.google.com/maps/place/YH+Studios+Photo+Studio/@25.1016195,55.1737819,17z/data=!3m1!4b1!4m6!3m5!1s0x3e5f6b44e4180c91:0x8d2c44cc959d713f!8m2!3d25.1016195!4d55.1737819!16s%2Fg%2F11bx88zfp1?entry=ttu&g_ep=EgoyMDI2MDUyMC4wIKXMDSoASAFQAw%3D%3D",
  latitude: "25.1016195",
  longitude: "55.1737819",
  rating: "",
  reviewsCount: "561",
  openingHours: "Open · Closes 7:30 pm · See more hours",
  logo: "/images/logo.png",
  images: ["/images/yh_studios_photo_studio_1779789138683_0.jpg", "/images/yh_studios_photo_studio_1779789139773_0.jpg", "/images/yh_studios_photo_studio_1779789140100_1.jpg", "/images/yh_studios_photo_studio_1779789140196_2.jpg", "/images/yh_studios_photo_studio_1779789140555_3.jpg", "/images/yh_studios_photo_studio_1779789140711_4.jpg", "/images/yh_studios_photo_studio_1779789140824_5.jpg", "/images/yh_studios_photo_studio_1779789140977_6.jpg", "/images/yh_studios_photo_studio_1779789141125_7.jpg", "/images/yh_studios_photo_studio_1779789141328_8.jpg", "/images/yh_studios_photo_studio_1779789141527_9.jpg", "/images/yh_studios_photo_studio_1779789141999_10.jpg", "/images/yh_studios_photo_studio_1779789142525_11.jpg", "/images/site_1779789152488_0.jpg", "/images/site_1779789152878_1.jpg", "/images/site_1779789153113_2.jpg", "/images/site_1779789153311_3.jpg", "https://usercontent.one/wp/yhstudiosdxb.com/wp-content/uploads/2021/03/partnersTLMI.jpg"],
  description: "",
}

export const aiContent = {
  tagline: "Capture Life's Moments",
  heroDescription: "Welcome to YH Studios Photo Studio, where our passion for photography meets your unique story. Our team of experts is dedicated to providing you with unforgettable experiences and stunning visuals. From headshots to weddings, we've got you covered.",
  aboutTitle: "Our Story, Focused on You",
  aboutText: "At YH Studios, we believe that every moment deserves to be captured with precision and care. Our state-of-the-art studio in Dubai is equipped with the latest technology, and our team of photographers is committed to delivering exceptional results. With years of experience in the industry, we've honed our skills to provide you with personalized services that exceed your expectations. Whether you're looking for a professional headshot or a romantic wedding shoot, we're here to help you tell your story.",
  services: [
    { icon: "📸", title: "Headshot Photography", description: "Professional headshots for individuals and corporations, tailored to your brand and style" },
    { icon: "📦", title: "Product Photography", description: "High-quality product images for e-commerce and marketing purposes, showcasing your products in the best light" },
    { icon: "💎", title: "Jewelry Photography", description: "Exquisite jewelry photography that highlights the beauty and craftsmanship of your pieces" },
    { icon: "🏠", title: "Real Estate Photography", description: "Stunning real estate photos that showcase properties in their best light, helping you sell or rent faster" },
    { icon: "📹", title: "Videography", description: "Cinematic videography services for events, weddings, and corporate projects, telling your story in motion" },
    { icon: "👰", title: "Wedding Photography", description: "Romantic and memorable wedding photography that captures the essence of your special day" }
  ],
  whyChooseUs: [
    { icon: "📚", title: "Experience", description: "Our team of photographers has years of experience in the industry, ensuring that you receive high-quality services" },
    { icon: "📸", title: "State-of-the-Art Equipment", description: "We use the latest technology and equipment to deliver exceptional results" },
    { icon: "👥", title: "Personalized Services", description: "We take the time to understand your unique needs and provide tailored services to meet your expectations" },
    { icon: "📊", title: "Competitive Pricing", description: "We offer competitive pricing without compromising on quality, ensuring that you receive the best value for your investment" }
  ],
  testimonials: [
    { name: "Fatima Al-Mansoori", role: "Bride", text: "YH Studios exceeded our expectations with their stunning wedding photography. The team was professional, friendly, and attentive to detail. We highly recommend them for any special occasion.", rating: 5 },
    { name: "Rashid Al-Khaja", role: "Entrepreneur", text: "I hired YH Studios for my company's headshot photography, and I was impressed with the quality of the images. The team was efficient, and the service was top-notch. I would definitely recommend them to anyone looking for professional photography services.", rating: 5 },
    { name: "Aisha Al-Suwaidi", role: "Model", text: "I had a fantastic experience working with YH Studios for my portfolio shoot. The team was creative, and the images turned out amazing. I would highly recommend them to anyone looking for high-quality photography services.", rating: 5 }
  ],
  portfolio: {
    categories: [
    { name: "Weddings", items: [
        { title: "Romantic Beach Wedding", description: "A beautiful wedding shoot at a stunning beach location", icon: "🏖️", image: "", category: "Weddings" },
        { title: "Luxury Hotel Wedding", description: "An elegant wedding shoot at a luxurious hotel", icon: "🏨", image: "", category: "Weddings" }
      ] },
    { name: "Portraits", items: [
        { title: "Corporate Headshots", description: "Professional headshots for business professionals", icon: "📸", image: "", category: "Portraits" },
        { title: "Family Portraits", description: "Heartwarming family portraits that capture the love and connection", icon: "👪", image: "", category: "Portraits" }
      ] },
    { name: "Products", items: [
        { title: "Jewelry Photography", description: "Exquisite jewelry photography that highlights the beauty and craftsmanship", icon: "💎", image: "", category: "Products" },
        { title: "Fashion Photography", description: "High-end fashion photography that showcases the latest trends and styles", icon: "👜", image: "", category: "Products" }
      ] },
    { name: "Real Estate", items: [
        { title: "Luxury Villas", description: "Stunning real estate photos of luxurious villas", icon: "🏠", image: "", category: "Real Estate" },
        { title: "Modern Apartments", description: "Sleek and modern real estate photos of apartments", icon: "🏢", image: "", category: "Real Estate" }
      ] }
    ]
  },
  pricing: {
    description: "Competitive pricing for all your photography needs",
    packages: [
    { name: "Basic", price: "$500", period: "per session", description: "Includes 1 hour of photography, 10 edited images, and a private online gallery", features: ["1 hour of photography", "10 edited images", "Private online gallery"], popular: false, cta: "Book Now" },
    { name: "Standard", price: "$1,200", period: "per session", description: "Includes 2 hours of photography, 20 edited images, and a private online gallery", features: ["2 hours of photography", "20 edited images", "Private online gallery"], popular: true, cta: "Book Now" },
    { name: "Premium", price: "$2,500", period: "per session", description: "Includes 4 hours of photography, 40 edited images, and a private online gallery", features: ["4 hours of photography", "40 edited images", "Private online gallery"], popular: false, cta: "Book Now" }
    ]
  },
  faq: {
    items: [
    { question: "What is the booking process?", answer: "To book a session, simply contact us through our website or give us a call. We will discuss your needs and provide you with a customized quote. A deposit is required to secure your booking, and the balance is due on the day of the shoot." },
    { question: "How long does a typical session take?", answer: "The length of a session varies depending on the type of photography and the number of people involved. On average, a session can take anywhere from 1 to 4 hours." },
    { question: "Do you provide editing services?", answer: "Yes, we provide editing services for all our photography sessions. Our team of experts will work with you to ensure that your images are edited to perfection." },
    { question: "Can I purchase additional images?", answer: "Yes, you can purchase additional images from your session. Please contact us for more information on our pricing and packages." },
    { question: "Do you offer discounts?", answer: "Yes, we offer discounts for bulk bookings and referrals. Please contact us for more information on our current promotions." },
    { question: "What is your cancellation policy?", answer: "We require a minimum of 24 hours' notice for cancellations. If you need to cancel or reschedule your session, please contact us as soon as possible to avoid any penalties." }
    ]
  },
  booking: {
    title: "Book Your Session Today",
    description: "Don't miss out on the opportunity to capture life's precious moments. Book your session today and let us help you tell your story."
  },
  events: {
    title: "Upcoming Events and Workshops",
    items: [
    { title: "Photography Workshop", description: "A hands-on workshop where you can learn the basics of photography and improve your skills", icon: "📸", date: "Ongoing", price: "From $200" },
    { title: "Wedding Photography Masterclass", description: "A comprehensive masterclass where you can learn the art of wedding photography and take your skills to the next level", icon: "👰", date: "March 2024", price: "From $500" },
    { title: "Photography Exhibition", description: "An exclusive exhibition featuring the work of local photographers and artists", icon: "🎨", date: "June 2024", price: "Free" },
    { title: "Portrait Photography Session", description: "A special session where you can get your portrait taken by a professional photographer", icon: "📸", date: "April 2024", price: "From $100" }
    ]
  },
  ctaTitle: "Capture Your Moment",
  ctaDescription: "Don't wait any longer to capture life's precious moments. Contact us today to book your session and let us help you tell your story.",
  ctaButtonText: "Book Now",
  metaDescription: "YH Studios Photo Studio: Capture life's moments with our expert photographers",
}

export const siteConfig = {
  layout: "default",
  sections: ["about", "services", "portfolio", "gallery", "pricing", "testimonials", "faq", "booking", "contact", "events", "blog"],
}
